// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: payment.proto

package paymentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PaymentProto_CreatePayment_FullMethodName = "/PaymentProto/CreatePayment"
)

// PaymentProtoClient is the client API for PaymentProto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentProtoClient interface {
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
}

type paymentProtoClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentProtoClient(cc grpc.ClientConnInterface) PaymentProtoClient {
	return &paymentProtoClient{cc}
}

func (c *paymentProtoClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, PaymentProto_CreatePayment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentProtoServer is the server API for PaymentProto service.
// All implementations must embed UnimplementedPaymentProtoServer
// for forward compatibility
type PaymentProtoServer interface {
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	mustEmbedUnimplementedPaymentProtoServer()
}

// UnimplementedPaymentProtoServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentProtoServer struct {
}

func (UnimplementedPaymentProtoServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentProtoServer) mustEmbedUnimplementedPaymentProtoServer() {}

// UnsafePaymentProtoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentProtoServer will
// result in compilation errors.
type UnsafePaymentProtoServer interface {
	mustEmbedUnimplementedPaymentProtoServer()
}

func RegisterPaymentProtoServer(s grpc.ServiceRegistrar, srv PaymentProtoServer) {
	s.RegisterService(&PaymentProto_ServiceDesc, srv)
}

func _PaymentProto_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentProtoServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentProto_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentProtoServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentProto_ServiceDesc is the grpc.ServiceDesc for PaymentProto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentProto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PaymentProto",
	HandlerType: (*PaymentProtoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentProto_CreatePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
