// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: organiser.proto

package organiserproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrganiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId uint64 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId  uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateOrganiserRequest) Reset() {
	*x = CreateOrganiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organiser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrganiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganiserRequest) ProtoMessage() {}

func (x *CreateOrganiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organiser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganiserRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganiserRequest) Descriptor() ([]byte, []int) {
	return file_organiser_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrganiserRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateOrganiserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateOrganiserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganiserId uint64 `protobuf:"varint,1,opt,name=organiser_id,json=organiserId,proto3" json:"organiser_id,omitempty"`
}

func (x *CreateOrganiserResponse) Reset() {
	*x = CreateOrganiserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organiser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrganiserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganiserResponse) ProtoMessage() {}

func (x *CreateOrganiserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organiser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganiserResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganiserResponse) Descriptor() ([]byte, []int) {
	return file_organiser_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganiserResponse) GetOrganiserId() uint64 {
	if x != nil {
		return x.OrganiserId
	}
	return 0
}

var File_organiser_proto protoreflect.FileDescriptor

var file_organiser_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4c, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x3c, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x51, 0x0a,
	0x09, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x12, 0x17, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x65, 0x76, 0x69, 0x6e, 0x6b, 0x69, 0x6d, 0x75, 0x74, 0x61, 0x69, 0x2f, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x61, 0x70, 0x70, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_organiser_proto_rawDescOnce sync.Once
	file_organiser_proto_rawDescData = file_organiser_proto_rawDesc
)

func file_organiser_proto_rawDescGZIP() []byte {
	file_organiser_proto_rawDescOnce.Do(func() {
		file_organiser_proto_rawDescData = protoimpl.X.CompressGZIP(file_organiser_proto_rawDescData)
	})
	return file_organiser_proto_rawDescData
}

var file_organiser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_organiser_proto_goTypes = []interface{}{
	(*CreateOrganiserRequest)(nil),  // 0: CreateOrganiserRequest
	(*CreateOrganiserResponse)(nil), // 1: CreateOrganiserResponse
}
var file_organiser_proto_depIdxs = []int32{
	0, // 0: Organiser.CreateOrganiser:input_type -> CreateOrganiserRequest
	1, // 1: Organiser.CreateOrganiser:output_type -> CreateOrganiserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_organiser_proto_init() }
func file_organiser_proto_init() {
	if File_organiser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_organiser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrganiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organiser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrganiserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_organiser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organiser_proto_goTypes,
		DependencyIndexes: file_organiser_proto_depIdxs,
		MessageInfos:      file_organiser_proto_msgTypes,
	}.Build()
	File_organiser_proto = out.File
	file_organiser_proto_rawDesc = nil
	file_organiser_proto_goTypes = nil
	file_organiser_proto_depIdxs = nil
}
